#ifndef PINOUT_H
#define PINOUT_H

#include "configuration.h"


#define MAKE_PIN_NAME_(port, pin) P##port##_##pin
#define MAKE_PIN_NAME(port, pin) MAKE_PIN_NAME_(port, pin)


#define PUSH_BUTTON_PIN MAKE_PIN_NAME(PUSH_BUTTON_PORT_NUMBER, PUSH_BUTTON_PIN_NUMBER)
#define PWR_SWITCH_PIN MAKE_PIN_NAME(PWR_SWITCH_PORT_NUMBER, PWR_SWITCH_PIN_NUMBER)
#define ROTARY_ENCODER_A_PIN MAKE_PIN_NAME(ROTARY_ENCODER_A_PORT_NUMBER, ROTARY_ENCODER_A_PIN_NUMBER)
#define ROTARY_ENCODER_B_PIN MAKE_PIN_NAME(ROTARY_ENCODER_B_PORT_NUMBER, ROTARY_ENCODER_B_PIN_NUMBER)
#define SEVEN_SEGMENT_DATA_PIN MAKE_PIN_NAME(SEVEN_SEGMENT_DATA_PORT_NUMBER, SEVEN_SEGMENT_DATA_PIN_NUMBER)
#define SEVEN_SEGMENT_CLK_PIN MAKE_PIN_NAME(SEVEN_SEGMENT_CLK_PORT_NUMBER, SEVEN_SEGMENT_CLK_PIN_NUMBER)


#endif // CONFIGURATION_H
